- name: prepare for classrom
  become: root
  hosts: local_server
  serial: 1
  tags: classroom
  roles:  
    - { role: virt-vms, when: lab == "openstack" }
    - { role: virt-k8s, when: lab == "kubernetes" }


#- name: SSH user key generator 
#  hosts: all
#  serial: 1
#  tags: sshkeygen
#  role:
#    - virt-ssh
