- name: install and enable to cri-o,docker enviroment
  hosts: k18s-master:k18s-node
  tags: k18s-prepare
  roles:  
    - { role: crio, when: crio_enviroment == true }
    - { role: docker, when: crio_enviroment == false }
    - { role: k18s-prepare }
