---
- name: copy kubelet config file to /etc/sysconfig
  copy:
    src: kubelet
    dest: /etc/sysconfig/kubelet

- name:
  service:
    name: kubelet
    state: restarted
    permanent: yes

- name: init kubeadmin with docker
  shell: kubeadm init --pod-network-cidr="{{ subnetnetwork }}" --apiserver-advertise-address="{{ apiserver_address }}"
  register: kube_discovery
